;; begin(elixir)
(add-to-list 'load-path "~/.emacs.d/plugins/alchemist.el")
(add-to-list 'load-path "~/.emacs.d/plugins/emacs-elixir")
(add-to-list 'load-path "~/.emacs.d/plugins/deps/pkg-info.el")
(add-to-list 'load-path "~/.emacs.d/plugins/deps/epl")
(autoload 'alchemist "alchemist" "alchemist mode" t)
(add-to-list 'auto-mode-alist '("\.ex$" . markdown-mode))
(add-to-list 'auto-mode-alist '("\.exs$" . markdown-mode))
(add-to-list 'auto-mode-alist '("\.html$" . html-mode))
;; end(elixir)
