;; begin(projectile)
(add-to-list 'load-path "~/.emacs.d/plugins/projectile")
(autoload 'projectile-find-file "projectile" "Projectile mode" t)
(autoload 'projectile-grep "projectile" "Projectile mode" t)
;;(require 'projectile)
(setq projectile-indexing-method 'alien)
;;(projectile-global-mode)
(global-unset-key (kbd "C-x f"))
(global-unset-key (kbd "C-x g"))
(global-set-key (kbd "C-x f") 'projectile-find-file)
(global-set-key (kbd "C-x g") 'projectile-grep)
;; end(projectile)
